AGENT_COMPENSATION_SAPI_RESTENDPOINT_URI:string
AUDIT_TRAIL_SAPI_RESTENDPOINT_URI:string
BILLING_ACCOUNT_SAPI_RESTENDPOINT_URI:string
BILLING_PAYMENT_SAPI_RESTENDPOINT_URI:string
CLAIM_ASSESSMENT_SAPI_RESTENDPOINT_URI:string
CLAIM_ASSIGNMENT_SAPI_RESTENDPOINT_URI:string
CLAIM_COVERAGE_SAPI_RESTENDPOINT_URI:string
CLAIM_PAPI_RESTENDPOINT_URI:string
CLAIM_PAYMENT_SAPI_RESTENDPOINT_URI:string
CLAIM_SAPI_RESTENDPOINT_URI:string
DMV_SAPI_LICENSE_RESTENDPOINT_URI:string
DOCUMENT_SAPI_RESTENDPOINT_URI:string
DOCUMENT_SERVICE_RESTENDPOINT_URI:string
ENDORSEMENT_SAPI_RESTENDPOINT_URI:string
EXASURE_DMV_SAPI_VIN_RESTENDPOINT_URI:string
FINANCE_PAPI_RESTENDPOINT_URI:string
FRAUD_EVALUATION_SAPI_RESTENDPOINT_URI:string
GENERAL_LEDGER_SAPI_RESTENDPOINT_URI:string
INVOICE_SAPI_RESTENDPOINT_URI:string
PAYABLE_SAPI_RESTENDPOINT_URI:string
POLICYHOLDER_PAPI_RESTENDPOINT_URI:string
POLICYHOLDER_SAPI_RESTENDPOINT_URI:string
POLICY_ADMIN_PAPI_QUOTE_DOCUMENTS_RESTENDPOINT_URI:string
POLICY_ADMIN_PAPI_QUOTE_RESTENDPOINT_URI:string
POLICY_ADMIN_PAPI_RESRENDPOINT_URI:string
POLICY_DOCUMENT_SAPI_RESTENDPOINT_URI:string
POLICY_PAPI_RESTENDPOINT_URI:string
POLICY_RENEWAL_SAPI_RESTENDPOINT_URI:string
POLICY_SAPI_RESTENDPOINT_URI:string
QUOTE_PAPI_RESTENDPOINT_URI:string
QUOTE_SAPI_RESTENDPOINT_URI:string
RECEIVABLES_SAPI_RESTENDPOINT_URI:string
REFUND_SAPI_RESTENDPOINT_URI:string
REINSTATEMENT_SAPI_RESTENDPOINT_URI:string
RESERVE_MANAGEMENT_SAPI_RESTENDPOINT_URI:string
SOCOTRA_POLICY_API_RESTENDPOINT_URI:string
SOCOTRA_POLICY_SAPI_RESTENDPOINT_URI:string
STRIPE_API_RESTENDPOINT_URI:string
TREASURY_SAPI_RESTENDPOINT_URI:string
USER_PAPI_RESTENDPOINT_URI:string
USER_SAPI_RESTENDPOINT_URI:string
