openapi: 3.0.1
info:
  title: agent-compensation-sapi-api
  description: API Definition of agent-compensation-sapi-api
  version: 1.0.0
servers:
- url: http://localhost:8290/agent-compensation-sapi-api
- url: https://localhost:8253/agent-compensation-sapi-api
paths:
  /agent-compensations:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /agents/{agentId}/statements/generate:
    post:
      parameters:
      - name: agentId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /agents/{quoteId}/agent-statements/quote:
    get:
      parameters:
      - name: quoteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /agents/{agentId}/statements:
    get:
      parameters:
      - name: agentId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /agents/fetch-all-agentStatement:
    get:
      responses:
        default:
          description: Default response
  /agents/{quoteId}/agent-statements/status:
    patch:
      parameters:
      - name: quoteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
