openapi: 3.0.1
info:
  title: b2c-xapi-api
  description: API Definition of b2c-xapi-api
  version: 1.0.0
servers:
- url: http://localhost:8290/b2c-xapi
- url: https://localhost:8253/b2c-xapi
paths:
  /api/{policyHolderId}:
    get:
      parameters:
      - name: policyHolderId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
    patch:
      parameters:
      - name: policyHolderId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/all/policyHolder:
    get:
      responses:
        default:
          description: Default response
  /api/policyHolder:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /policyAPI/{policyId}:
    get:
      parameters:
      - name: policyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /api/policy:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/policy/{policyId}/issuance:
    patch:
      parameters:
      - name: policyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/policy/{policyId}/cancellation:
    patch:
      parameters:
      - name: policyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/all/policy:
    get:
      responses:
        default:
          description: Default response
  /api/policyholder/{policyHolderId}/policies:
    get:
      parameters:
      - name: policyHolderId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /api/quote/{quoteId}:
    get:
      parameters:
      - name: quoteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /api/quote/{quoteId}/accept:
    patch:
      parameters:
      - name: quoteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/quote/{quoteId}/discard:
    patch:
      parameters:
      - name: quoteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/quote:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/policyHolder/{policyHolderId}:
    get:
      parameters:
      - name: policyHolderId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /signup:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /login:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /claim:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /claim/{claimId}/reject:
    patch:
      parameters:
      - name: claimId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /claim/{claimId}:
    get:
      parameters:
      - name: claimId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /claim/{claimId}/validate:
    get:
      parameters:
      - name: claimId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /claim/{claimId}/accept:
    patch:
      parameters:
      - name: claimId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /claim/policyHolder/{policyHolderId}:
    get:
      parameters:
      - name: policyHolderId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
