openapi: 3.0.1
info:
  title: claim-sapi
  description: API Definition of claim-sapi
  version: 1.0.0
servers:
- url: http://localhost:8290/claim-sapi/api
- url: https://localhost:8253/claim-sapi/api
paths:
  /claim/{claimId}:
    get:
      parameters:
      - name: claimId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /claim:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /claim/{claimId}/reject:
    patch:
      parameters:
      - name: claimId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /claim/{claimId}/accept:
    patch:
      parameters:
      - name: claimId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /claim/settlement:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /claim/policyHolder/{policyHolderId}:
    get:
      parameters:
      - name: policyHolderId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
