openapi: 3.0.1
info:
  title: claim-payment-sapi
  description: API Definition of claim-payment-sapi
  version: 1.0.0
servers:
- url: http://localhost:8290/claim-payment-sapi/api
- url: https://localhost:8253/claim-payment-sapi/api
paths:
  /payment/store/transaction:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /payment/retrieve/claimsPaymentDetails:
    get:
      responses:
        default:
          description: Default response
  /payment/retrieve/{transactionId}:
    get:
      parameters:
      - name: transactionId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /payment/retrive/{paymentId}:
    get:
      parameters:
      - name: paymentId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /payment/payout:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /payment/token:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
