openapi: 3.0.1
info:
  title: endorsement-sapi
  description: API Definition of endorsement-sapi
  version: 1.0.0
servers:
- url: http://localhost:8290/endorsement-sapi
- url: https://localhost:8253/endorsement-sapi
paths:
  /policies/{policyId}/endorsements:
    post:
      parameters:
      - name: policyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/policies/{policyId}/endorsements:
    get:
      parameters:
      - name: policyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /api/endorsements/{endorsementId}/validate:
    post:
      parameters:
      - name: endorsementId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/endorsements/{endorsementId}:
    get:
      parameters:
      - name: endorsementId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /endorsements/{endorsementId}/accept:
    patch:
      parameters:
      - name: endorsementId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/endorsements/{endorsementId}/issue:
    patch:
      parameters:
      - name: endorsementId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /endorsements/{endorsementId}/discard:
    patch:
      parameters:
      - name: endorsementId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
