openapi: 3.0.1
info:
  title: finance-papi-api
  description: API Definition of finance-papi-api
  version: 1.0.0
servers:
- url: http://localhost:8290/finance-papi-api
- url: https://localhost:8253/finance-papi-api
paths:
  /treasury/transactions/{treasuryAccountId}:
    get:
      parameters:
      - name: treasuryAccountId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
