openapi: 3.0.1
info:
  title: general-ledger-sapi
  description: API Definition of general-ledger-sapi
  version: 1.0.0
servers:
- url: http://localhost:8290/general-ledger-sapi/api
- url: https://localhost:8253/general-ledger-sapi/api
paths:
  /entries:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /entries/quotes/{quoteId}:
    get:
      parameters:
      - name: quoteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
    patch:
      parameters:
      - name: quoteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /entries/claims/{claimId}:
    get:
      parameters:
      - name: claimId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
    patch:
      parameters:
      - name: claimId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
