openapi: 3.0.1
info:
  title: policyHolder-papi-api
  description: API Definition of policyHolder-papi-api
  version: 1.0.0
servers:
- url: http://localhost:8290/policyHolder-papi
- url: https://localhost:8253/policyHolder-papi
paths:
  /api/{policyHolderId}:
    get:
      parameters:
      - name: policyHolderId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
    patch:
      parameters:
      - name: policyHolderId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/policyHolder:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/policyholder/{policyHolderId}/policies:
    get:
      parameters:
      - name: policyHolderId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /api/all/policyHolder:
    get:
      responses:
        default:
          description: Default response
