openapi: 3.0.1
info:
  title: policy-sapi-api
  description: API Definition of policy-sapi-api
  version: 1.0.0
servers:
- url: http://localhost:8290/policy-sapi
- url: https://localhost:8253/policy-sapi
paths:
  /api/{policyId}:
    get:
      parameters:
      - name: policyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /api/policy:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/policy/{policyNumber}/issuance:
    patch:
      parameters:
      - name: policyNumber
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/policy/{policyNumber}/cancellation:
    patch:
      parameters:
      - name: policyNumber
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /api/all/policy:
    get:
      responses:
        default:
          description: Default response
