openapi: 3.0.1
info:
  title: refund-sapi-api
  description: API Definition of refund-sapi-api
  version: 1.0.0
servers:
- url: http://localhost:8290/refund-sapi/api
- url: https://localhost:8253/refund-sapi/api
paths:
  /refunds/retrieve/cancelPolicyDetails:
    get:
      responses:
        default:
          description: Default response
  /refunds/create:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /refunds/store-refund:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /refunds/retrieve/{refundId}:
    get:
      parameters:
      - name: refundId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
