openapi: 3.0.1
info:
  title: reserve-management-sapi
  description: API Definition of reserve-management-sapi
  version: 1.0.0
servers:
- url: http://localhost:8290/reserve-management-sapi
- url: https://localhost:8253/reserve-management-sapi
paths:
  /api/claim/{claimId}/reserves:
    get:
      parameters:
      - name: claimId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
    post:
      parameters:
      - name: claimId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
    patch:
      parameters:
      - name: claimId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
